app:
  name: "web_app"
  mod:  "dev"
  port: 8088
  start_time: "2022-01-01"
  machineID: 1


log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql"
  dbname: "sql_demo"
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  poolsize: 100
